language: python
python:
  - 3.5
install:
  - pip install -r requirements.txt
script:
  - python3 manage.py test
env:
  global:
    - DJANGO_SETTINGS_MODULE="meetuppizza.settings.base"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
